Run full update loop on individual failures

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -63,10 +63,15 @@ jobs:
       - name: Run update-script
         run: |
           set -o pipefail
+          exit_code=0
           echo "$UPDATE_NIX_ATTRS" | jq --raw-output '.[]' | while read -r attr; do
             printf "\n\n==== Updating %s ====\n" "$attr" >&2
-            UPDATE_NIX_ATTR_PATH="$attr" nix run --file ./internal/update-script.nix
+            if ! UPDATE_NIX_ATTR_PATH="$attr" nix run --file ./internal/update-script.nix; then
+              printf "ERROR: Update failed for %s\n" "$attr" >&2
+              exit_code=1
+            fi
           done
+          exit $exit_code
         env:
           FLAKE_URI: ${{ github.workspace }}
           UPDATE_NIX_ATTRS: ${{ steps.attrs.outputs.attrs }}
